---

services:

  authelia:
    container_name: 'authelia'
    image: 'authelia/authelia'
    restart: 'unless-stopped'
    networks:
      net:
        aliases: []
    expose:
      - 9091
    volumes:
      - './authelia:/config'
    environment:
      PUID: '1112'
      PGID: '501'
      TZ: 'Europe/Berlin'

...
