identity_validation:
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'
    jwt_secret: 'nSqgXLvl94gQBQn8Wd6E4fAKcRaO08I0ai1yhBwReJ1N9oN13LhKRvQhgQb61Dgc'
authentication_backend:
  refresh_interval: '5m'
  password_reset:
    disable: false
    custom_url: ''
  file:
    path: '/config/users_database.yml'
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16
      scrypt:
        iterations: 16
        block_size: 8
        parallelism: 1
        key_length: 32
        salt_length: 16
      pbkdf2:
        variant: 'sha512'
        iterations: 310000
        salt_length: 16
      sha2crypt:
        variant: 'sha512'
        iterations: 50000
        salt_length: 16
      bcrypt:
        variant: 'standard'
        cost: 12




storage:
  encryption_key: 'BkSrkwhhgcQd0cbgZ0bhvdNadkT96bqZU1X8V1AG7FIKcHGbRmlj943tGJKjw6at'
  local:
    path: '/config/db.sqlite3'




session:
  secret: 'LgHdJ9oGJTOJF5mPuJdXZfymPGQ3E5cuzneKTfVq6B1R0S4Z6blgmQd1ahked5DU'
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'cosy-juelich.duckdns.org'
      authelia_url: 'https://auth.cosy-juelich.duckdns.org'
      default_redirection_url: 'https://www.cosy-juelich.duckdns.org'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'


notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'


access_control:
  default_policy: 'deny'
  networks:
  - name: 'internal'
    networks:
    - '10.0.0.0/8'
    - '172.16.0.0/12'
    - '192.168.0.0/18'
  rules:
  - domain: 'private.cosy-juelich.duckdns.org'
    domain_regex: '^(\d+\-)?priv-img\.cosy-juelich\.duckdns.org$'
    policy: 'one_factor'
    networks:
    - 'internal'
    - '1.1.1.1'
    subject:
    - ['user:mike']
    - ['user:tine']
    - ['group:admins']
    methods:
    - 'GET'
    - 'HEAD'
    resources:
    - '^/api.*'
    query:
    - - operator: 'present'
        key: 'secure'
      - operator: 'absent'
        key: 'insecure'
    - - operator: 'pattern'
        key: 'token'
        value: '^(abc123|zyx789)$'
      - operator: 'not pattern'
        key: 'random'
        value: '^(1|2)$'
  - domain: 'app.cosy-juelich.duckdns.org'
    policy: 'bypass'
    resources:
    - '^/api([/?].*)?$'
